# Generated by Django 2.2.dev20181005132628 on 2018-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twistter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttext',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='profile',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
