# Generated by Django 2.2.dev20181005132628 on 2018-11-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twistter', '0003_auto_20181114_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account',
            new_name='username',
        ),
    ]
