# Generated by Django 2.2.dev20181005132628 on 2018-11-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twistter', '0005_auto_20181119_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
